modules/developers-guide/examples/stargate-rest-api.postman_collection.json
=> update REST API examples in Postman collection

modules/developers-guide/pages/graphql.adoc, modules/developers-guide/pages/rest.adoc
=> Fix qs links

modules/developers-guide/nav.adoc, modules/developers-guide/pages/metrics.adoc, modules/developers-guide/partials/docker_compose.adoc
=> Add metrics page for stargate with prometheus and grafana

modules/developers-guide/pages/cql-using.adoc, modules/developers-guide/pages/document-using.adoc, modules/developers-guide/pages/graphql-using.adoc, modules/developers-guide/pages/install/install_docker.adoc, modules/developers-guide/pages/install/install_existing_cstar.adoc, modules/developers-guide/pages/rest-using.adoc, modules/developers-guide/partials/astra_tip.adoc, modules/quickstart/pages/quick_start-document.adoc, modules/quickstart/pages/quick_start-graphql.adoc, modules/quickstart/pages/quick_start-rest.adoc
Add Astra tips to pages, to alert users to Astra existence.
=> Add astra tips

modules/developers-guide/pages/install/building.adoc
=> add jdk8 as a req for building sg

antora.yml, modules/developers-guide/pages/install/install_dse_68.adoc, modules/developers-guide/partials/docker_run_dse_68.adoc, modules/developers-guide/partials/docker_run_existing_dse_68.adoc
=> dse fixes for typos

modules/developers-guide/examples/cql/create_index_list_sai.cql, modules/developers-guide/examples/cql/create_index_map_sai.cql, modules/developers-guide/examples/cql/create_index_set_sai.cql, modules/developers-guide/pages/rest-using.adoc
https://github.com/stargate/docs/issues/49
=> add SAI info for REST API/DSE

api/new/DevOpsv1.yaml, api/new/StargateDocv2.yaml, api/new/StargateRESTv1.yaml, api/new/StargateRESTv2.yaml, modules/developers-guide/examples/json/Stargate_Document_API_users.postman_collection.json, modules/developers-guide/examples/json/Stargate_Document_API_users_Astra.postman_collection.json, modules/developers-guide/examples/json/Stargate_GraphQL_API_library.postman_collection.json, modules/developers-guide/examples/json/Stargate_GraphQL_API_library_Astra.postman_collection.json, modules/developers-guide/examples/json/Stargate_REST_API_users_keyspace_Astra.postman_collection.json, modules/developers-guide/examples/json/Stargate_REST_v2_API_users_keyspace.postman_collection.json
Need a public location to link to for astra postman stargate collections.
=> add astra postman to stargate repo

antora.yml, modules/developers-guide/pages/install/install_vm_cass_3x.adoc, modules/developers-guide/pages/install/install_vm_cass_40.adoc, modules/developers-guide/pages/install/install_vm_dse_68.adoc
Update docker version and DSE 6.8 document hyperlink
=> Update docker version and DSE 6.8 document hyperlink

modules/developers-guide/pages/install/install_vm_cass_3x.adoc, modules/developers-guide/pages/install/install_vm_cass_40.adoc, modules/developers-guide/pages/install/install_vm_dse_68.adoc, package.json
Per Madhavan, I'm fixing a link. I discovered a minor typo in package.json and fixed it, too (missing comma at end of a line).
=> fix starctl command link, minor typo in package.json

modules/developers-guide/examples/json/Stargate Astra API Environment.postman_environment.json, modules/developers-guide/examples/json/Stargate OSS API Environment.postman_environment.json, modules/developers-guide/examples/json/Stargate-OSS-Astra-Document-API-myworld.postman_collection.json, modules/developers-guide/examples/json/Stargate-OSS-Astra-GraphQL-API-library.postman_collection.json, modules/developers-guide/examples/json/Stargate-OSS-Astra-REST-API-users_keyspace.postman_collection.json
Referenced in a new astra-docs page (will add to stargate docs later).
=> Add new postman stuff

site-local.yaml, site-publish.yaml
I've been meaning to add this feature for awhile.
=> add prev/next pagination to docs

modules/ROOT/nav.adoc, modules/ROOT/pages/tooling.adoc
Add page that references postman tooling resources.
=> Add tooling page

site-local.yaml, site-publish.yaml
https://github.com/stargate/docs/issues/41
Simple change that should direct any user to the right GH place to fork and submit a change.
=> add Edit page url to antora.yaml

.github/workflows/antora.yml, .github/workflows/publish.yaml
=> Revert "fix attachments in gh action run"

modules/developers-guide/pages/document-using.adoc
https://datastax.jira.com/browse/C2-1195
=> typos in document-using

modules/developers-guide/partials/GQLNaming.adoc
https://github.com/stargate/docs/issues/86
=> make gql naming table the same in astra and stargate

modules/ROOT/pages/api.adoc, modules/developers-guide/examples/graphql/curl_deleteIndex.sh, modules/developers-guide/examples/graphql/deleteIndex.graphql, modules/developers-guide/examples/graphql/durl_deleteInex.sh, modules/developers-guide/examples/rest/curl_create_addl_indexes.sh, modules/developers-guide/examples/rest/curl_create_index.sh, modules/developers-guide/examples/rest/curl_delete_index.sh, modules/developers-guide/examples/rest/curl_get_indexes.sh, modules/developers-guide/examples/result/gql_deleteIndex.result, modules/developers-guide/examples/result/rest_curl_create_addl_indexes.result, modules/developers-guide/examples/result/rest_curl_create_index.result, modules/developers-guide/examples/result/rest_curl_get_indexes.result, modules/developers-guide/pages/create-an-index-rest.adoc, modules/developers-guide/pages/delete-an-index-rest.adoc, modules/developers-guide/pages/graphql-using.adoc, modules/developers-guide/pages/rest-using.adoc, modules/developers-guide/pages/rest.adoc
https://github.com/stargate/docs/issues/67
=> Add create/delete index to graphql cql-first (and rest-using)

modules/developers-guide/pages/graphql-first-using.adoc, modules/developers-guide/partials/docker_run.adoc
polandll feel free to clean this up however you want. I just wanted to get an example in that enables the graphql-first flag and was trying to follow the existing pattern.
=> Add docker run partial with graphql-first flag enabled

api/StargateDocv2.yaml
Remove Document API v0 predicates that were never implemented.
=> fix doc api oas yaml

api/StargateDocv2.yaml
Add the batch write endpoint into the docs, remove `pretty` parameter as it never existed in the actual API
=> Add batch endpoint, remove `pretty`

api/StargateDocv2.yaml
Resolves https://github.com/stargate/docs/issues/148
=> Remove `sort` parameter

.github/workflows/antora.yml, .github/workflows/publish.yaml
The attachments need to be regenerated each time the docs are updated. I added 3 steps for REST v2, REST v1, and Doc v2.
=> add redoc-cli actions to gh action yaml files

modules/developers-guide/pages/authnz.adoc
=> Add a paragraph describing auth_tokenttl system property

modules/developers-guide/examples/json/Stargate-OSS-Astra-REST-API-users_keyspace.postman_collection.json, modules/developers-guide/examples/rest/curl_add_udt_to_table.sh, modules/developers-guide/examples/rest/curl_create_udt.sh, modules/developers-guide/examples/rest/curl_delete_udt.sh, modules/developers-guide/examples/rest/curl_get_udt.sh, modules/developers-guide/examples/rest/curl_insert_udt_data.sh, modules/developers-guide/examples/rest/test.sh, modules/developers-guide/examples/result/rest_curl_create_udt.result, modules/developers-guide/examples/result/rest_curl_get_udt.result, modules/developers-guide/pages/rest-using.adoc
Still working on this, but opening the pr
=> Create udt rest

README.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/tooling.adoc, modules/concepts/pages/concepts.adoc, modules/developers-guide/pages/go-processing.adoc, modules/developers-guide/pages/graphql.adoc, modules/developers-guide/pages/rust-developing.adoc, modules/quickstart/pages/quick_start-rest.adoc, site-local.yaml, site-publish.yaml
Followup on broken links from Aleks.
=> fix broken links, mostly master -> main

modules/developers-guide/examples/json/Stargate-OSS-Astra-REST-API-users_keyspace.postman_collection.json
Updates to REST collection to remove GQL steps that are no longer needed and fix a couple of test cases that were failing
=> Updating REST Postman collection

modules/developers-guide/examples/json/Stargate-OSS-Astra-Document-API-myworld.postman_collection.json, modules/developers-guide/examples/json/Stargate-OSS-Astra-GraphQL-API-library.postman_collection.json, modules/developers-guide/examples/json/Stargate-OSS-Astra-REST-API-users_keyspace.postman_collection.json
I exported the new Postman collections from the new Postman workspace, and am replacing the current files.
=> update postman collections

.github/workflows/linkinator.yml
Issue #200 
I'm trying out a GH action cron job to run a link checker once a week.
=> add cron job to run linkinator every week

docs-src/stargate-develop/modules/develop/pages/tooling.adoc
Pieter requested that the links to postman items point to the DS Astra Workspace at postman.com
=> DOC-3242 Point Postman collections and environments to Postman workspace

docs-src/stargate-develop/modules/develop/pages/api-doc/doc-document-operators.adoc, docs-src/stargate-develop/modules/develop/pages/dev-with-doc.adoc
Just a couple of typos to fix.
=> fix typos in $or 

docs-src/stargate-develop/modules/develop/pages/sdks/doc-nodejs-client.adoc, docs-src/stargate-develop/modules/develop/pages/sdks/rest-nodejs-client.adoc
=> DOC-2963 fix node js sdk

docs-src/stargate-develop/modules/develop/pages/tooling.adoc
=> fix Document api for swagger ui in stargate

package.json, package.json.orig
Get rid of dependencies that are not needed.
=> cleanup package.json, but keep the original

docs-src/stargate-develop/modules/develop/partials/astra_tip.adoc
Added base URL for Astra DB to make it easy on the Astra DB API users.
=> Add base URL for Astra DB

.github/workflows/build.yml, .github/workflows/publish.yml
Updated versionf of [`JamesIves/github-pages-deploy-action`](https://github.com/JamesIves/github-pages-deploy-action/releases) & [`peaceiris/actions-gh-pages`](https://github.com/peaceiris/actions-gh-pages/releases).
=> Updated versions
